server:
  port: 8080

spring:
  application:
    name: e-commerce-application
  datasource:
    url: jdbc:mysql://localhost:3306/edb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update